= Function List
This is a list of all the functions that are related to the User Interface, not the API documentation!

== main.py
* Random Line From HUMBLE:
** Just as advertised, it just displays a random line from HUMBLE by Kendrick Lamar

* Enter Password:
** If this is your first time setup, or if you deleted ./credentials/passwd.txt, this prompt will appear.
** It covers the input, so it looks like you're not typing anything, but you are.
** It'll then generate salts and hash it, and store it in (passwd.txt)

* The Main Prompt:
** If you press 1, it'll stop the program.
** If you press 2, it'll loop back to (connector.py)
** If you press 3, it'll run  (master-bill.py) and get the total of all bills made today.
*** Don't worry about accidentally running it, it'll always rewrite the file, so run it as many
times as you want.
*** It'll automatically generate a weekly sales report (./sales_reports/**) With The Grand Totals Of 7 Days.
If there's < 7 Days after the initial, It'll have no issue, it'll mention them.
** If you press 4, it'll take you to (sql-client.py) where you can view and alter entries.
** If you press 5, it'll take you to (verify.py) where you can verify your bills.
** If you press 6, it'll take you to an interface, allowing you to modify your configuration.
** If you selected 'Bank Transfer Mode' there'll be a number 7, which will allow you to track who sent transfers and didn't.
*** There's two functions, view transactions and edit transactions.
*** In view, it displays all the transactions (If there are multiple under the same name, it'll display the time)
*** In edit, it shows you the transactions, prompts you for a name, and you can edit if they've transfered or not.

== connector.py
* ID Prompt (ID: )
** When it prompts for the ID, you may enter the ID number, and proceed.
** If you want to view the current total enter '--' instead of an ID when prompted.
** Once you're certain that all the items are in order, press (enter) without any text, to proceed to the invoice
** You may enter any of the following to get to the following (#Rhymes)
*** del
*** Kill
*** update

* View Display ([shows the bill])
** To enter this screen, type '--' in the ID prompt
** **If you only want to see the total, and not checkout yet, please use this instead of (enter)**
** It'll show you all the items in the cart and the subtotal.

* Invoice Prompt (Cash Given: )
** To enter this screen , press (enter) without any other input in the ID Prompt.
** Enter the discount %, if there's no discount, enter 0 (Even if you don't it'll automatically assign 0)
** After it returns the Total, enter the amount of cash given, if the balance is negative, it keeps asking you for the correct amount, until you give the correct amount.
** Afterwards, it returns the balance, then goes back to main.py
** **NOTE: If you selected "Bank Transfer Mode" it'll ask you if they have transfered or not, instead of asking for amount payed and balance.**

* Delete Prompt (The (Name) To Be Removed: )
** To enter this screen, type 'del' in the ID prompt.
** Enter the item name of what you wish to delete (The names will be displayed)
** If successful, it'll say so. Or else, it'll loop until you provide the correct name.

* Kill Prompt (Enter Password: )
** To enter this screen, type 'Kill' in the ID Prompt.
** You will have to enter the password you set in (main.py). Once you set it, there is no way to reset or recover it. As it's stored
as a hash in (passwd.txt), it has 2 salts, on either side of the text.
** It covers the input, so it looks like you're not typing anything, but you are.
** If successful, it'll kill the process, make sure you delete the Bill manually, if you tried to checkout before doing the above.

* Update Prompt (What Would You Like To Update? (Name): )
** To enter this screen, type 'update' in the ID Prompt.
** You'll be prompted to enter the name of the Item, (all items are shown above the prompt)
** Afterwards, it'll ask you to input the quantity you want to add / substract
** You have to enter '+' for addition and '-' for substraction, leave a space and enter the amount you want to add.
*** **NOTE: The Space Is Very Important**
*** Eg: '+ 20' not '+20'


== verify.py
* "Verify or Hash or Quit? (v/h/q): "
** If you press 'v', it'll use its existing registry of Hashes and verify if the files hashes are the same
** If they are it'll say '<file> Is The Same'
** If they aren't it'll say '<file> Has Been Tampered'
** If you press 'h', it'll hash all the new bills and store the hashes (skipping existing ones)

== sql-client.py
- Master Password:
    - Enter the master password you set in (main.py)
- Smilin_DB> :
[source,asciidoc]
----
        Getting Data:
            show all        -> shows all dolls
            show specific   -> allows you to set one condition
            show advanced   -> allows you to set multiple conditions
            show custom     -> write your own search query (for the paddigurlTest and Removed table only)

        Inserting Data:
            add             -> adds an item, prompts for Name and Price
            add id          -> adds an item, prompts for ID, Name and Price
            add multiple    -> adds items(s), prompts for Name and Price

        Modifying Data:
            update          -> Update the name and price of an item
            delete          -> removes an item from paddigurlTest and adds it to paddigurlRemoved

        Miscellaneous:
            help            -> displays this
            bye             -> quit
----