= Logs

== 22nd May 2021
I made this random program to test out if I could extract data from a MySQL Server
And Add Them All And Get The Balance. And it succeeded! After 3 Days of trying I gave up on it
But then randomly picked it up 3 weeks later, and fixed the bugs!

== 29th May 2021
Added a billing system. So now all progress is logged properly, and saved. Instead of specifying how many items there
can be, you keep on adding items, and when you're done, hit enter in the ID input (without any text) and it'll
process the data and create an invoice.

== 12th June 2021
Hello, my silent friend (get the reference?) its been a while. I added many new files, including a master-bill
maker, an SQL Client and a File Integrity checker. Added new features like Password Recovery, automatic setup scripts
deleting and updating capabilities and making sales reports. Today, I added a new feature I just learned, Classes. So to reduce
the repetitive commands, which were copy+pasted everywhere, can now be in a centralized class! It reduces cluttering and makes editing
the code easier!

== 7th July 2021
The credentials are now entered on your first setup, and stored in a file (Encrypted of Course)
and each time you run Main.py its Decrypted, instead of making the rest of the files (connector, verify) also decrypt it
main.py sends the credentials as a CL Argument. And the RSA Key is now stored in the logs, so whenever its deleted
 you can recover it. And I added different phases to main.py, Init0 which checks your log file, Init1 which looks for
 your SQL Credentials, Init3 which checks for code updates and Init5 which checks the integrity of all the files in ./credentials

== 15th July 2021
The program can run two ways, either as a compiled .exe file, or from source. If its compiled, you don't need to
install python or anything, just the file and README.md (For reference). If you're Git Cloning and running the .py
files, then you have to install the requirements (main.py will do it for you) and all. So its all upto your preference.

== 18th July 2021
Successfully made GitHub actions compile two versions of the program (Linux and Windows), it now auto publishes them to a
release draft. GitHub Actions is very hard and lacks a lot of documentation, specially for Python. Also created a docker-compose.yml format
in configuration.py so you get the option to create a docker container at startup.

== 21st October 2021
I recently discovered this framework called "rich" for python. So I installed it, and boy was it amazing!
I replaced all the text with the "colours" class earlier with rich. I also added functions like warn, info and all
Instead of the old boring tables, now there's an alive one, thanks again, to rich! (when you click --)
I also changed the bill format from .txt to markdown. So now I have styled it colours and all, and of course
changed all the other files accordingly (was quite a pain, but worth it).

== 23rd November 2021
I randomly remembered that JSON (JavaScript Object Notation) Exists, and forgot that the format the
hashes were stored in is nothing more than in a text file, separated by commas (disappointing). I was contemplating
whether to use TOML (Tom's Obvious Minimal Language), but then decided that TOML is more user friendly (which
is not what I'm looking for, since the machine is the one that interacts with this file) than powerful. I could've
used YAML, but JSON looked nicer (I know, bad excuse, but hey, my program). And why not XML? Go look at an XML
document and then speak to me. So now the hashes are stored in a JSON File (credentials/hashes.json)

== 12th January 2022
Within the span of yesterday and today, alot of things happened to the code. I merged a branch called 'code-clean' which
I used to clean the code and look for bugs and all. And I found fixes for issues that've been there for so long, yet
I never know existed. I also optimized the code and rewrote a few functions. At the time of writing, I transferred
the docs from Markdown to Asciidoc and am about to merge that pull request tomorrow.